language: python
python:
  - "3.5.2"

install:
  - "pip install -r requirements.txt"

script:
  - "pytest"
  - "coverage run src/*coverage run src/*"

after_success:
  - coveralls
  
notifications:
  email:
    - kyoje11@gmail.com