#!/usr/local/bin/python3
# Author : Nesoy

from src.Database import Database
from src.Printer import Printer
import sys

database = None
printer = None
databaseName = "todolist.db"
tableName = "todo"

def init():
    global database
    global printer
    database = Database()
    database.createDatabase(databaseName)
    database.createTable(tableName)
    printer = Printer()

def main(argv):
    init()
    todoList = database.getTodoList("TODO")
    doingList = database.getTodoList("DOING")
    doneList = database.getTodoList("DONE")
    
    if(len(argv) > 1):
        # Printing
        if(argv[1] == "list"):
            printer.printTodoList(todoList)
            printer.printDoingList(doingList)
        if(argv[1] == "all"):
            printer.printTodoList(todoList)
            printer.printDoingList(doingList)
            printer.printDoneList(doneList)
        if(argv[1] == "doing"):
            printer.printDoingList(doingList)
        if(argv[1] == "done"):
            printer.printDoneList(doneList)

        # CRUD
        if(argv[1] == "add"):
            database.insertTodo("TODO", argv[2])
        if(argv[1] == "start"):
            index = int(argv[2])-1
            database.updateStatus(todoList[index][0],"DOING")
            database.updateStartTime(todoList[index][0])
        if(argv[1] == "end"):
            index = int(argv[2])-1
            database.updateStatus(doingList[index][0],"DONE")
            database.updateEndTime(doingList[index][0])

            # Todo : Check argv Size
            # remove only todo list -> update doing, done 
            # Todo : Search
    else:
        printer.printTodoList(todoList)
        printer.printDoingList(doingList)
        printer.printDoneList(doneList)

if __name__ == "__main__":
    main(sys.argv)
