#!/usr/local/bin/python3
# Author : Nesoy

import sqlite3 as sqlite
import sys

DATABASE_NAME = "todolist.db"
conn = sqlite.connect(DATABASE_NAME)

# Magic Number
TODO = ' '
DOING = 'DOING'
DONE = 'O'

# SQL
SQL_GET_LIST = "SELECT * FROM task WHERE status = (?)"
SQL_DELETE_TODO = "DELETE FROM task WHERE id=(?)"
SQL_UPDATE_TODO = "UPDATE task SET status = (?) WHERE id=(?)"

def init():
    global conn
    with conn:
        cur = conn.cursor()
        cur.execute("CREATE TABLE IF NOT EXISTS task(id INTEGER PRIMARY KEY, status TEXT, description TEXT)")

# CREATE
def addTodo(param):
    global conn
    with conn:
        cur = conn.cursor()
        sql = "INSERT INTO task(status, description) values (?,?)"
        cur.execute(sql, [TODO, param])
        conn.commit()

# READ
def getTodoList():
    return getList(TODO)

def getDoingList():
    return getList(DOING)

def getDoneList():
    return getList(DONE)

def getList(param):
    global conn
    todoList = [] # empty todolist
    with conn:
        cur = conn.cursor()
        cur.execute(SQL_GET_LIST, [param])
        for task in cur.fetchall():
            todoList.append(task)
        return todoList

# REMOVE
def removeTodo(todoList, index):
    global conn
    id = todoList[int(index)-1][0]
    with conn:
        cur = conn.cursor()
        sql = SQL_DELETE_TODO
        cur.execute(sql, [id])
        conn.commit()

# UPDATE        
def startTodo(todoList, index):
    global conn
    id = todoList[int(index)-1][0]
    with conn:
        cur = conn.cursor()
        sql = SQL_UPDATE_TODO
        cur.execute(sql, [DOING, id])
        conn.commit()

def endTodo(todoList, index):
    global conn
    id = todoList[int(index)-1][0]
    with conn:
        cur = conn.cursor()
        sql = SQL_UPDATE_TODO
        cur.execute(sql, [DONE, id])
        conn.commit()

# PRINT
def printAllList():
    printTodoList()
    printDoingList()
    printDoneList()

def printTodoList():
    todoList = getTodoList()
    printList("# Todo List", todoList)

def printDoingList():
    todoList = getDoingList()
    printList("# Doing List", todoList)

def printDoneList():
    todoList = getDoneList()
    printList("# Done List", todoList)

def printList(listName, todoList):
    print(listName)
    if(len(todoList) > 0):
        index = 1
        for todo in todoList:
            print("[" + str(index) + "] " + todo[1] + " : " + todo[2])
            index += 1



def main(argv):
    init()
    if(argv[1] == "add"):
        addTodo(argv[2])
    if(argv[1] == "list"):
        if(len(argv) > 2):
            if(argv[2] == "all"):
                printAllList()
            if(argv[2] == "done"):
                printDoneList()
        else:
           printTodoList()

    if(argv[1] == "remove"):
        # Todo : Check argv Size
        todoList = getTodoList()
        removeTodo(todoList, argv[2])
    if(argv[1] == "start"):
        todoList = getTodoList()
        startTodo(todoList, argv[2])
    if(argv[1] == "end"):
        todoList = getDoingList()
        endTodo(todoList, argv[2])

if __name__ == "__main__":
        main(sys.argv)
